version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: go-ddd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: go_ddd
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docs/sql/mysql-init:/docker-entrypoint-initdb.d
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  redis:
    image: redis:7
    container_name: go-ddd-redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.6
    container_name: go-ddd-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode (no zookeeper)
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"

      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-init:
    image: bitnami/kafka:3.6
    container_name: go-ddd-kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "
      echo 'waiting kafka...';
      sleep 8;
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user.events --partitions 1 --replication-factor 1;
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user.events.dlq --partitions 1 --replication-factor 1;
      echo 'kafka topics ready';
      "

volumes:
  mysql_data:
  kafka_data:
