app:
  name: go-ddd-template
  env: dev

http:
  addr: ":8080"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s

log:
  level: info


db:
  mysql:
    dsn: "root:password@tcp(127.0.0.1:3306)/go_ddd?parseTime=true&loc=Local&multiStatements=true"
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 30m

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  user_ttl: 10m

kafka:
  brokers: ["127.0.0.1:9092"]
  user_topic: "user.events"
